### ISSUE TITLE
https://storage.googleapis.com/tekton-releases/results/latest/release.yaml returns an old version

### ISSUE THREAD

**Issue by sm43** [tektoncd/results#138]
# Expected Behavior
https://storage.googleapis.com/tekton-releases/results/latest/release.yaml
should return the latest release version 
at present it is v0.3.1

# Actual Behavior

returns an older version v0.1.1

# Steps to Reproduce the Problem

1. https://storage.googleapis.com/tekton-releases/results/latest/release.yaml
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by wlynch** [comment]
Good catch! Deleted the file. Rely on `https://storage.googleapis.com/tekton-releases/results/previous/${RELEASE_VERSION}/release.yaml` instead
