### ISSUE TITLE
PipelineRuns are not recorded if re-triggered from Tekton dashboard

### ISSUE THREAD

**Issue by drriguz** [tektoncd/results#150]
Hi there,
I found that the tekton result database only records pipelineruns that triggered from event listener, however if I re-run the pipeline directly from the tekton dashboard, then nothing changes in the database. No new records will be inserted, nor the update_time of the previous record will be updated.

Is this by design?

Thanks!

**Comment by wlynch** [comment]
Sorry for missing this issue!

A new run of a Pipeline is considered a new event, so it should create new Result and Record (it won't try to group this within the previous result).

If that's not the case, let me know and I can try to reproduce (let me know what dashboard/result versions you're using).
