### ISSUE TITLE
Simpleui does not work with port-forward

### ISSUE THREAD

**Issue by drriguz** [tektoncd/results#151]
# Expected Behavior
When I use `kubectl port-forward -n tekton-pipelines service/tekton-results-api-service 50051:50051` and then run the simple ui, I should be able to see the results page

# Actual Behavior
The `go run .` command hangs and the simple ui page could not be opened.

# Steps to Reproduce the Problem

1. Install tekton-results in cluster by following the guide
2. run simple ui locally
3. try to open simple ui

# Additional Info

- Kubernetes version:

```
  Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:03:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1
```

- Tekton Pipeline version:

v0.29.0

The reason I've figured out is that grpc.withInsecure() will not work if there is tls configured in server side, however even if I add the cert file with `grpc.WithTransportCredentials`, still I'll get error says that "Unable to find token", which comes from rbac.go.

I've little experience in Go so I guess I'm not able to fix it...

**Comment by melnikalex** [comment]
Can we re-open this issue? Would be sweet to have this work out of the box.

**Comment by khrm** [comment]
I am reopening this issue. I never tried sinpleui? What benefit it gives in comparison to grpc UI clients? 

/reopen
