### ISSUE TITLE
Record PipelineRun and TaskRun results

### ISSUE THREAD

**Issue by lcarva** [tektoncd/results#204]
### Feature request

PipelineRuns and TaskRuns can emit results. For example, the git-clone Task produces the `commit` result with "the precise commit SHA that was fetched". It would be great to store this information in the corresponding records.

### Use case

I have a task that takes as a parameter an image reference, provides various assessments on it, then creates a summary report. This report is made available outside the Task via a Task result. I want to use Tekton Results to persist these reports, so I can have a historical view of this data.

**Comment by adambkaplan** [comment]
@dibyom @wlynch looks like this issue can be closed as fixed?
