### ISSUE TITLE
Data Race in watcher reconciler test

### ISSUE THREAD

**Issue by dibyom** [tektoncd/results#228]
# Expected Behavior
No data race in unit tests

# Actual Behavior
From https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_results/226/pull-tekton-results-unit-tests/1565331909276340224

```
WARNING: DATA RACE
Read at 0x00c0006d7243 by goroutine 81:
  testing.(*common).logDepth()
      /usr/local/go/src/testing/testing.go:753 +0xa6
  testing.(*common).log()
      /usr/local/go/src/testing/testing.go:746 +0x8f
  testing.(*common).Logf()
      /usr/local/go/src/testing/testing.go:792 +0x21
  testing.(*T).Logf()
      <autogenerated>:1 +0x75
  go.uber.org/zap/zaptest.testingWriter.Write()
      /home/prow/go/pkg/mod/go.uber.org/zap@v1.22.0/zaptest/logger.go:130 +0x153
  go.uber.org/zap/zaptest.(*testingWriter).Write()
      <autogenerated>:1 +0xad
  go.uber.org/zap/zapcore.(*ioCore).Write()
      /home/prow/go/pkg/mod/go.uber.org/zap@v1.22.0/zapcore/core.go:90 +0x1e7
10 skipped lines...
  knative.dev/pkg/controller.(*Impl).processNextWorkItem()
      /home/prow/go/pkg/mod/knative.dev/pkg@v0.0.0-20211115071955-517ef0292b53/controller/controller.go:542 +0x72f
  knative.dev/pkg/controller.(*Impl).RunContext.func3()
      /home/prow/go/pkg/mod/knative.dev/pkg@v0.0.0-20211115071955-517ef0292b53/controller/controller.go:478 +0x6c
Previous write at 0x00c0006d7243 by goroutine 35:
  testing.tRunner.func1()
      /usr/local/go/src/testing/testing.go:1180 +0x52c
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1197 +0x22a
Goroutine 81 (running) created at:
  knative.dev/pkg/controller.(*Impl).RunContext()
      /home/prow/go/pkg/mod/knative.dev/pkg@v0.0.0-20211115071955-517ef0292b53/controller/controller.go:476 +0x21a
  knative.dev/pkg/controller.StartAll.func1()
      /home/prow/go/pkg/mod/knative.dev/pkg@v0.0.0-20211115071955-517ef0292b53/controller/controller.go:789 +0xaf
Goroutine 35 (finished) created at:
  testing.(*T).Run()
      /usr/local/go/src/testing/testing.go:1238 +0x5d7
  testing.runTests.func1()
      /usr/local/go/src/testing/testing.go:1511 +0xa6
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1193 +0x202
  testing.runTests()
      /usr/local/go/src/testing/testing.go:1509 +0x612
  testing.(*M).Run()
      /usr/local/go/src/testing/testing.go:1417 +0x3b3
  main.main()
      _testmain.go:49 +0x236
```

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by adambkaplan** [comment]
Looks like the issue here is that the controllers and test are using the same logger, and the controllers are running in a separate goroutine. Since this depends on pipeline repo code, it may be hard to untangle.

@dibyom can we convert these to run the controller reconcile functions serially?

**Comment by dibyom** [comment]
> @dibyom can we convert these to run the controller reconcile functions serially?

Yeah, not sure how much effort that is but that sounds like a more better way of testing this

**Comment by adambkaplan** [comment]
Race condition likely arises from here: https://github.com/tektoncd/results/blob/main/pkg/watcher/reconciler/reconciler_test.go#L51-L53

I think to resolve this, we should:

1. Ensure that unit-level (synchronous) tests check the result annotation is set
2. Ensure that e2e (asynchronous) tests check the result annotation is set

**Comment by enarha** [comment]
With the e2e tests now enabled and the same functionality covered by the TestTaskRun and TestPipelineRun tests, I see 3 options going forward with this and unblocking the release:

1. Remove the unit tests.
2. Keep the unit tests, but skip them. They can be later used as a basis for improvement.
3. Improve the tests making them synchronous as suggested earlier. This will be the most time consuming and this task is not the highest in my priority list, but I'll eventually get to it.

Opinions?

**Comment by adambkaplan** [comment]
I am in favor of option 1 - we have the same test as proper E2Es at both the TaskRun and PipelineRun level:

- https://github.com/tektoncd/results/blob/main/test/e2e/e2e_test.go#L95-L98
- https://github.com/tektoncd/results/blob/main/test/e2e/e2e_test.go#L146-L149

**Comment by enarha** [comment]
#316 was merged. The issue can be closed.

**Comment by adambkaplan** [comment]
Faulty test was re-added in https://github.com/tektoncd/results/commit/073b4707f7d3941b0e2932ee96fa11518d6e5249
