### ISSUE TITLE
Release results v0.5.0

### ISSUE THREAD

**Issue by dibyom** [tektoncd/results#237]
Its' been a while since the last release and there have been a few features (RecordSummary, ppc64le support, rest proxy) along with a bunch of bug fixes since then.

I don't see docs on creating a release but I think all you have to do is to run tekton/release-run.yaml (assuming you have access to the dogfooding cluster)

- [ ] Run the release pipeline
- [ ] Create a git tag
- [ ] Add release notes

**Comment by dibyom** [comment]
Running the pipeline: `tkn --context dogfooding pr logs -f results-release-api-ghfrl`

**Comment by dibyom** [comment]
Unit test for ppc64le seems to be failing consistently - Think we need to fix https://github.com/tektoncd/results/issues/228 first


```
env:
  - name: GOOS
    value: linux
  - name: GOARCH
    value: ppc64le
  - name: GO111MODULE
    value: auto
image: 'docker.io/library/golang:latest'
name: unit-test
resources: {}
script: |
  SRC_PATH="$GOPATH/src/$(workspaces.source.path)/.../."
  mkdir -p $SRC_PATH
  cp -R "$(workspaces.source.path)"/"."/* $SRC_PATH
  cd $SRC_PATH
  go test -cover -v ./...
  
```

[results-release-api-7mm22-unit-tests-ppc64le-pod__step-unit-test__log.txt](https://github.com/tektoncd/results/files/9636247/results-release-api-7mm22-unit-tests-ppc64le-pod__step-unit-test__log.txt)

**Comment by christianvogt** [comment]
Any update on when we can expect a new release?

**Comment by khrm** [comment]
I think we should do a release after https://github.com/tektoncd/results/pull/258 
@vdemeester @adambkaplan

**Comment by vdemeester** [comment]
@khrm either just after, or just before (as it might not be completely stable) ?

**Comment by adambkaplan** [comment]
@khrm @vdemeester I would do it before. We need to do quite a bit of rework, and I am going to close #258 so that we land it in more containable chunks.

**Comment by adambkaplan** [comment]
We have a release! https://github.com/tektoncd/results/releases/tag/v0.5.0
