### ISSUE TITLE
Generate an access log from the apiserver

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/results#246]
### Feature request

Log all requests to the Results apiserver to stdout. This can be accomplished using grpc interceptors from [grpc-ecosystem](https://github.com/grpc-ecosystem/go-grpc-middleware).

### Use case

* Generate an access log for audit/compliance purposes.
* Record request durations and responses for debugging.

**Comment by khrm** [comment]
Fixed by #275

**Comment by adambkaplan** [comment]
/close

I believe this has been fixed (at one point we had a regression, but it was resolved).
