### ISSUE TITLE
Working Group Zoom Meeting

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/results#263]
# Discussion

From today's Tekton Governing Board meeting:

Since there has been growing interest and contributions to Tekton Results, we should run a regular working group meeting so that contributors can meet synchronously and in the open. We can utilize the Tekton community's Zoom account to run the meeting, and Google Drive to store meeting notes.

Items that we need to agree upon:

- [ ] Meeting cadence - weekly, biweekly, etc.
- [ ] Day of week to meet
- [ ] Meeting time - note that some projects alternate meeting times to accommodate timezone differences.

Once that it is set, it is a matter of setting up the Zoom meeting, creating the running notes doc, and updating the list of [working groups](https://github.com/tektoncd/community/blob/main/working-groups.md)

**Comment by dibyom** [comment]
I'd start with biweekly, previously we'd send out a survey of some times that don't conflict with existing working groups and pick the winner as the day/time to meet

**Comment by adambkaplan** [comment]
Looking at the Tekton calendar, these are times that could work:

- Monday **1:30 pm UTC (8:30AM EST/ 7:00 pm IST) (Europe + Asia), 6PM UTC (1PM EST/11:30PM IST) Europe + NA)**
- Tuesday - this is pretty booked, I don't recommend.
- Wednesday **1:30 pm UTC (8:30AM EST/ 7:00 pm IST) (Europe + Asia), 6PM UTC (1PM EST/11:30PM IST) Europe + NA)**
- Thursday **12:30 pm UTC (7:30AM EST/ 6:00 pm IST) (Europe + Asia), 5:30PM UTC (12:30PM EST/11PM IST) Europe + NA)**

**Comment by adambkaplan** [comment]
I think we should also ask preferred cadence (weekly/bi weekly), and preferred time (Asia friendly vs NA-friendly)

**Comment by adambkaplan** [comment]
Survey is up: https://forms.gle/HCBGpMzFMmzUhKss9

**Comment by adambkaplan** [comment]
The results are in. There were 16 responses total:

- 50% indicated EST was their closest time zone. 25% indicated an EMEA-friendly time zone, 25% indicated an IST.
- Majority preference was to meet every two weeks (56%), there was no consensus for meeting more frequently than that.
- There was a general even distribution of preferred meeting times. The top preferred times:
  - Monday 13:30 UTC (8)
  - Thursday 17:30 UTC (8)
  - Thursday 12:30 UTC (7)
  - Wednesday 13:30 UTC (7)

Given these results, I propose the following schedule:

- Every two weeks on Thursday
- Alternate between 12:30 UTC and 17:30 UTC

Any strong objections?

**Comment by avinal** [comment]
The working group meeting is set. This should be closed.
