### ISSUE TITLE
Translating CEL ordering/filtering to REST API requests

### ISSUE THREAD

**Issue by avinal** [tektoncd/results#378]
The filtering/ordering of the responses when using gRPC is handled by CEL expressions. We need to investigate how this function can be used while consuming the REST endpoints. Followup from discussion in the Slack: https://tektoncd.slack.com/archives/C01GCEH0FLK/p1677743586629099

- If this is possible to use CEL expression in REST requests?
- If yes, how? Document the process and update OpenAPI Spec.
- If no, alternatives. May need a new feature to be added.

**Comment by manuelwallrapp** [comment]
I had the same issues and it took me some time to setup the REST calls with filtering and pagination, even though pagination doesn't work properly as I understood. 

There is definitely need for more documentation and examples. Also how to access over REST.

**Comment by avinal** [comment]
Hey @manuelwallrapp, it would be great if you can share your findings and what topics you think are missing. I am actively working on better documentation for Tekton Results. You can see #377 for debugging using REST and API docs.

**Comment by avinal** [comment]
Thanks for sharing. I will look into all other queries as well and include them in the API docs.

**Comment by avinal** [comment]
Hi @manuelwallrapp, can you please review #377, and suggest if something is missing/should be added, and also if it covers this issue?

**Comment by avinal** [comment]
The issue was resolved in #377
