### ISSUE TITLE
Release Pipeline doesn't tag image as v0.5.0

### ISSUE THREAD

**Issue by khrm** [tektoncd/results#400]
# Expected Behavior

Images should be tagged as v0.5.0
# Actual Behavior
The tag doesn't exist as per the discussion.

**Comment by khrm** [comment]
@enarha Can you check why this is happening? Otherwise, I will look into this later.  AFAIK, using ko should give us a tag with the version.

@vdemeester

**Comment by khrm** [comment]
I think I found the issue. I would confirm and then raise a pr. @enarha

**Comment by adambkaplan** [comment]
/close

Fixed!
