### ISSUE TITLE
Watcher can't handle initial load of TaskRuns (around 80'000) and Pipelineruns (around 20'000)

### ISSUE THREAD

**Issue by manuelwallrapp** [tektoncd/results#403]
# Expected Behavior
The Watcher loads all pipelinerun and taskrun into the Database. We have around 80'000 Taskruns and 20'000 Pipelineruns.

# Actual Behavior

It just can't start the informers. On a Cluster with less Tekton ressources the watcher starts just fine. The Debug log of the Watcher looks as following. After it crashes. Is there any option to increase the timeout?

2023/03/17 17:10:47 dialing tekton-results-api-service.esta-tekton-results.svc.cluster.local:50051...
2023/03/17 17:10:47 Unable to inject logs client, logs will not be stored: logs service not enabled in server
2023/03/17 17:10:47 Registering 3 clients
2023/03/17 17:10:47 Registering 2 informer factories
2023/03/17 17:10:47 Registering 2 informers
2023/03/17 17:10:47 Registering 2 controllers
{"level":"debug","time":"2023-03-17T17:10:47.724Z","caller":"logging/config.go:116","msg":"Successfully created the logger."}
{"level":"debug","time":"2023-03-17T17:10:47.724Z","caller":"logging/config.go:117","msg":"Logging level set to: debug"}
{"level":"info","time":"2023-03-17T17:10:47.724Z","logger":"watcher","caller":"profiling/server.go:64","msg":"Profiling enabled: false","commit":"9f84a1f-dirty"}
{"level":"info","time":"2023-03-17T17:10:47.729Z","logger":"watcher","caller":"leaderelection/context.go:47","msg":"Running with Standard leader election","commit":"9f84a1f-dirty"}
{"level":"debug","time":"2023-03-17T17:10:47.732Z","logger":"watcher","caller":"metrics/metrics_worker.go:76","msg":"Flushing the existing exporter before setting up the new exporter.","commit":"9f84a1f-dirty"}
{"level":"debug","time":"2023-03-17T17:10:47.732Z","logger":"watcher","caller":"metrics/prometheus_exporter.go:51","msg":"Created Prometheus exporter with config: &{tekton.dev/results watcher prometheus 5000000000 <nil>  false 9090 0.0.0.0}. Start the server for Prometheus exporter.","commit":"9f84a1f-dirty"}
{"level":"debug","time":"2023-03-17T17:10:47.732Z","logger":"watcher","caller":"metrics/metrics_worker.go:91","msg":"Successfully updated the metrics exporter; old config: <nil>; new config &{tekton.dev/results watcher prometheus 5000000000 <nil>  false 9090 0.0.0.0}","commit":"9f84a1f-dirty"}
{"level":"info","time":"2023-03-17T17:10:47.732Z","logger":"watcher","caller":"logs/client.go:49","msg":"Unable to fetch Logs Client from context, either disabled from config or disabled from server side","commit":"9f84a1f-dirty"}
{"level":"info","time":"2023-03-17T17:10:47.732Z","logger":"watcher","caller":"logs/client.go:49","msg":"Unable to fetch Logs Client from context, either disabled from config or disabled from server side","commit":"9f84a1f-dirty"}
{"level":"info","time":"2023-03-17T17:10:47.738Z","logger":"watcher","caller":"sharedmain/main.go:283","msg":"Starting configuration manager...","commit":"9f84a1f-dirty"}
{"level":"info","ts":1679073047.8393128,"logger":"fallback","caller":"injection/injection.go:63","msg":"Starting informers..."}

# Steps to Reproduce the Problem

1. Have a cluster with 20'000 Pipelineruns and 80'000 Taskruns. 
2. Start the Api then the Watcher
3. Watcher stops at starting informers

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
Client Version: 4.9.8
Server Version: 4.11.28
Kubernetes Version: v1.24.6+deccab3
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**
Client version: 0.29.1
Pipeline version: v0.37.5
Triggers version: v0.20.2

**Comment by manuelwallrapp** [comment]
Ok, I could load this amount of data with more than 10Gb Memory. So it consumes just an huge amount of memory, but then works.

**Comment by adambkaplan** [comment]
/close

Worth noting "add RAM" as a performance tuning option. Filed #412 so we can document this and other performance tuning options.
