### ISSUE TITLE
Configure Watcher when to delete old PipelineRuns and TaskRuns - retention time

### ISSUE THREAD

**Issue by manuelwallrapp** [tektoncd/results#411]
### Feature request

We would like to be able to configure how long the PipelineRun and TaskRuns will stay on the cluster till deleted. It would be great to configure a retention time.

### Use case

We start a lot of Pipelines with Tekton and when they fail we want to analyze them. We would like to have the option to let them for one day on the cluster or so, that also the user of the pipeline has the chance to navigate through PipelineRuns and TaskRuns with the standard Tekton Pipeline Ui.

**Comment by alan-ghelardi** [comment]
@manuelwallrapp  this is what the `-completed_run_grace_period` Watcher's flag does:

```yaml
- -completed_run_grace_period
        - 24h # or whatever value you consider more suitable
        ```

Is that what you were looking for or would you like to configure the retention for each run (say, via an annotation)?

**Comment by manuelwallrapp** [comment]
Yeah I found it as well shortly after I posted the question but forgot to answer it here. Thank you. Diving into the code helps.
