### ISSUE TITLE
Upgrade knative/pkg to latest 1.8 or 1.9 commits

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/results#423]
### Feature request

knative 1.8 and 1.9 include a significant performance fix that recently merged. This can reduce CPU usage by as much as 60% at scale.

### Use case

See https://github.com/tektoncd/pipeline/issues/6193 for further discussion.

**Comment by alan-ghelardi** [comment]
In addition to performance improvements, I noticed recently that the leader election is broken in the knative.dev/pkg version currently used in the Results project.
