### ISSUE TITLE
Document how to add another config overlay

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/results#427]
### Feature request

Add a `README` that describes how to add an overlay configuration for Tekton Results.

### Use case

In https://github.com/tektoncd/results/commit/39b0981e668a7731481dcd9e79457b3e2bb84b3d I reorganized how the yaml manifests for Results are organized. Contributors and end users can't use the current `base` directory by itself without losing some important information - they must create an overlay or use the `default-local-db` overlay. We need to describe how to create an overlay, and which components must be included.

**Comment by enarha** [comment]
Covered by https://github.com/tektoncd/results/pull/447
/close
