### ISSUE TITLE
Provide Database Migration Scripts for #334

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/results#429]
### Feature request

Provide database migration scripts alongside schema changes from #334.

### Use case

* Provide supported scripting for those who wish to disable auto migration.
* Add scripts in the event a schema change cannot be automatically migrated by gorm. This was the case with #334 (could not covert column type to `jsonb`).

**Comment by khrm** [comment]
Do we need to reopen this? @adambkaplan

**Comment by adambkaplan** [comment]
I know @sayan-biswas drafted one for Red Hat (we were deploying on a live, running service). Since this project is alpha from a community support standpoint, maybe just linking that script here is sufficient.

**Comment by Fabian-K** [comment]
That would be much appreciated :)
