### ISSUE TITLE
New release v0.6.0

### ISSUE THREAD

**Issue by enarha** [tektoncd/results#434]
This issue serves as a tracker for the upcoming v0.6.0 release scheduled for Apr 17th.

**Comment by adambkaplan** [comment]
@enarha @khrm it looks like we published the release last week :tada: 

Have we sent out announcements to the tekton-dev and tekton-users mailing lists?

**Comment by khrm** [comment]
@adambkaplan I had announced this in #results channel. Forgot to announce in mailing list and #general channel of slack.

**Comment by avinal** [comment]
We can close this issue now.
