### ISSUE TITLE
Make e2e tests more configurable

### ISSUE THREAD

**Issue by avinal** [tektoncd/results#437]
### Feature request

Currently, the e2e test uses various **hard-coded** parameters for the scenarios around testing with kind clusters only. We do have some environment variables for fetching tokens and ssl certs. Following the same path, we should review other parameters that would make it easier to run tests with different kinds of setups.

Especially the `serverName` and `serverAddress` variables. 

Refer here:

https://github.com/tektoncd/results/blob/fdc47542cc0ce52fadaa4389a01ff0c2b75fe6e5/test/e2e/e2e_test.go#L59-L70

### Use case

- In a case where results is deployed on a remote server
- Results is deployed in a different namespace

**Comment by adambkaplan** [comment]
+1 on this - it would be great if the e2e test script allows the tests to be run against a real deployment on a production cluster.

Variables that probably need/should be tunable:

- `serverName` - unclear if this is needed on a real deployment?
- `serverAddress` - this will definitely need to be tuned if Results is exposed via an `Ingress` object, `LoadBalancer` service, etc.
- `certFileName` - this probably won't be needed if the server address uses a publicly trusted certificate - ex, if the `Ingress` uses a LetsEncrypt TLS cert.
