### ISSUE TITLE
CEL Filters across Results return multiple duplicate records

### ISSUE THREAD

**Issue by adambkaplan** [tektoncd/results#450]
# Expected Behavior

When using a CEL filter over the REST API that is likely to return a unique record, only one record should be returned.

Example:

Running `curl` against `https://<host>/apis/results.tekton.dev/v1alpha2/parents/default/results/-/records` with the following CEL expression as the `filter` query parameter:

```
data_type == "tekton.dev/v1beta1.PipelineRun" && data.metadata.name == "sum-three-pipeline-run-v2zcx"
```

(the pipeline ran with a generated name)

# Actual Behavior

The same `PipelineRun` records from the database are returned 5 times.

```
$ curl -G -s --insecure --data-urlencode "filter=data_type == \"tekton.dev/v1beta1.PipelineRun\" && data.metadata.name == \"sum-three-pipeline-run-v2zcx\"" -H "Authorization: Bearer $token" -H "Accept: application/json" https://localhost:8080/apis/results.tekton.dev/v1alpha2/parents/cdcon-demo/results/-/records | jq '[ .records[] | {"name": .name, "id": .id, "uid": .uid, "data_type": .data.type } ]'
[
  {
    "name": "cdcon-demo/results/7144a6f4-d904-4395-b85d-22c7f593a8e5/records/7144a6f4-d904-4395-b85d-22c7f593a8e5",
    "id": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "uid": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "data_type": "tekton.dev/v1beta1.PipelineRun"
  },
  {
    "name": "cdcon-demo/results/7144a6f4-d904-4395-b85d-22c7f593a8e5/records/7144a6f4-d904-4395-b85d-22c7f593a8e5",
    "id": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "uid": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "data_type": "tekton.dev/v1beta1.PipelineRun"
  },
  {
    "name": "cdcon-demo/results/7144a6f4-d904-4395-b85d-22c7f593a8e5/records/7144a6f4-d904-4395-b85d-22c7f593a8e5",
    "id": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "uid": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "data_type": "tekton.dev/v1beta1.PipelineRun"
  },
  {
    "name": "cdcon-demo/results/7144a6f4-d904-4395-b85d-22c7f593a8e5/records/7144a6f4-d904-4395-b85d-22c7f593a8e5",
    "id": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "uid": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "data_type": "tekton.dev/v1beta1.PipelineRun"
  },
  {
    "name": "cdcon-demo/results/7144a6f4-d904-4395-b85d-22c7f593a8e5/records/7144a6f4-d904-4395-b85d-22c7f593a8e5",
    "id": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "uid": "d8fe373e-5ef4-4dc0-8f15-46dd8c2b5522",
    "data_type": "tekton.dev/v1beta1.PipelineRun"
  }
]
```

# Steps to Reproduce the Problem

1. Run a few pipelines with Tekton Results installed and correctly reconciling.
2. Use `tkn pipeline start` to run a pipeline with a generated name.
3. Use the REST API to query records across all results in the parent namespace, searching for a pipeline with a generated name

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  Client Version: v1.27.1
  Kustomize Version: v5.0.1
  Server Version: v1.26.3
  ```

- Tekton Pipeline version:
  
  ```
  Client version: 0.30.1
  Pipeline version: v0.44.2
  ```

**Comment by adambkaplan** [comment]
Would #404 potentially fix this?

**Comment by alan-ghelardi** [comment]
>Would #404 potentially fix this?
I hope so. There are a couple of issues related to the current implementation that I'm trying to solve with this pull request. Did you catch this bug in the OpenShift installation? Would be possible to deploy that pull request there to confirm?

Another collaborator found various issues related to search and pagination at https://github.com/tektoncd/results/issues/379. I'm waiting for his tests to make sure that they were resolved.

**Comment by sayan-biswas** [comment]
@adambkaplan
I wanted to fix this, but I am not able to reproduce this. Am I missing something?

![image](https://user-images.githubusercontent.com/2537717/236253086-fc29c16f-f52f-4c5d-bca6-ee6d53aa240d.png)

**Comment by avinal** [comment]
I am getting similar results as Sayan.

**Comment by manuelwallrapp** [comment]
I tested this PR https://github.com/tektoncd/results/pull/404, in my test szenario it worked.

**Comment by adambkaplan** [comment]
/close

Perhaps part of my issue is that I experienced this issue when I was testing a demo script, which created/deleted the same namespace and pipelinerun over and over again. I was also running this locally on a `kind` cluster with rootless podman, and the container running the cluster was regularly started and stopped.

I'm inclined to close this as "not reproducible" - if someone does encounter this issue on a real cluster with a real PostgresDB instance (on cluster or external), it is worth reopening.
