### ISSUE TITLE
Database SSL Mode `verify-ca` or `verify-full` with a custom CA certificate

### ISSUE THREAD

**Issue by iainsproat** [tektoncd/results#531]
# Expected Behavior

Given a custom root CA certificate for a postgres database server, I would like postgres to use `verify-ca` or `verify-full` SSL modes using the custom CA certificate.

Is there a mechanism for achieving this that maybe I have missed?

# Actual Behavior

With the existing kubernetes manifests, there does not seem to be a mechanism for mounting a trusted certificate either in postgres default location [or by specifying a custom location to postgres](https://github.com/tektoncd/results/blob/e85794158c43defca77deb2b63201497dca9f45d/cmd/api/main.go#L94).

# Steps to Reproduce the Problem

1. Configure Results with either `DB_SSLMODE=verify-ca` or `DB_SSLMODE=verify-full`.
2. Provide a trusted certificate to Results to be used by postgres.
3. Results API should undertake SSL verification using the trusted certificate when connecting, but does not.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

  ```
  (paste your output here)
  ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`**

**Comment by adambkaplan** [comment]
/kind feature

Agree this would be a net new feature, as Results would need to do the following:

1. Provide a means for the database certificate authority (CA) to be (optionally) mounted at a known path in the apiserver deployment.
2. Ensure that the path to the database CA is passed into the Postgres connection string, via the `sslrootcert` parameter.

See [PostgreSQL SSL docs](https://www.postgresql.org/docs/current/libpq-ssl.html) for further technical information.

**Comment by adambkaplan** [comment]
/lifecycle frozen

This is an important security feature.

**Comment by enarha** [comment]
@iainsproat, when you have a chance please TAL at #658. It implements the feature you asked for. Thanks.
