### ISSUE TITLE
Support filtering of `Results` using name of the PipelineRun/TaskRun

### ISSUE THREAD

**Issue by avinal** [tektoncd/results#610]
### Feature request

Currently there is no filtering option that can search for result created for a particular PipelineRun/TaskRun. The current flow is to search for records and then find the result name from them. 

There should be a filtering option that can directly be applied to the `Results` using PipelineRun/TaskRun name.

### Use case

This feature will be useful in:
- For dashboards where the user is trying to populate data about a Run. This feature will cut down on number of API calls and bandwidth used. 

### Approach

We can add a new annotation to the Result.Summary that contains the name of the PipelineRun/TaskRun creating that results. The current path is `records.data.metadata.name`. After adding annotation the filter for results can be used as

```sh
filter='summary.annotations["RunName"]=="name"'
```
There can be other approaches as well.

**Comment by avinal** [comment]
cc @enarha

**Comment by cmorinupgrade** [comment]
Any progress on that front? That's something we would consider contributing at some point if there is no active work done on this. We need this feature to integrate the dashboard with the results api. I like the approach you suggested @avinal . It sounds like a quick win that could be put in place relatively fast.

**Comment by adambkaplan** [comment]
Don't we support this with CEL filtering?
