### ISSUE TITLE
resultAnnotations are nonfunctional

### ISSUE THREAD

**Issue by benbrittain** [tektoncd/results#614]
# Expected Behavior
Metadata annotated on a pipeline run is propagated to the Result

# Actual Behavior
No metadata annotations

# Steps to Reproduce the Problem

1. Create a PipelineRun with annotations 
2. Run the PipelineRun
3. Query the Results API

# Additional Info

- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3", GitCommit:"25b4e43193bcda6c7328a6d147b1fb73a33f1598", GitTreeState:"clean", BuildDate:"2023-06-14T09:53:42Z", GoVersion:"go1.20.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.3-gke.100", GitCommit:"6466b51b762a5c49ae3fb6c2c7233ffe1c96e48c", GitTreeState:"clean", BuildDate:"2023-06-23T09:27:28Z", GoVersion:"go1.20.5 X:boringcrypto", Compiler:"gc", Platform:"linux/amd64"}
```
- Tekton Pipeline version:

v0.50.0

**Comment by khrm** [comment]
It's fixed in latest release v0.52. Hopefully, it will be fixed in 0.50.2

/assign @khrm

**Comment by benbrittain** [comment]
I should be able to upgrade to 0.52 (not changing the results deployment) and this will be fixed?

**Comment by benbrittain** [comment]
I can indeed it seems
