### ISSUE TITLE
Persist TaskRun logs with timestamps (opt-in)

### ISSUE THREAD

**Issue by thomascube** [tektoncd/results#671]
### Feature request

I'd like to have timestamp information in the logs persisted by Tekton Results.
Basically the equivalent of `kubectl logs --timestamps`

Of course this should be opt-in and configurable by a config option.

### Use case

For long running pipeline tasks, exact timing information for each log line can be helpful to determine where the elapsed time was spent. We have a custom UI built for Tekton which can show/hide timestamps in logs. Instead of pulling the logs ourselves, we'd like to use Tekton results' logging feature to persist logs and consume them via the API.

**Comment by manuelwallrapp** [comment]
We also need this feature. Eventually we can figure out how to adapt it and do a PR.

**Comment by thomascube** [comment]
This feature is now covered with the merge of #789.
