### ISSUE TITLE
[integrations] Tekton CLI

### ISSUE THREAD

**Issue by wlynch** [tektoncd/results#81]
Tracking issue for integrating with tkn, the [Tekton CLI](https://github.com/tektoncd/cli).

We'd like to add support for querying the Results API via tkn. This can likely be done in a non-invasive way via [tkn plugins](https://github.com/tektoncd/cli/commit/247384276c1d4cbf4855390bc20e765c6881fe66).

Interesting things to figure out here include:
- How can users connect to the API if it's local to the cluster? Does it need to be a publicly available service, or is there a lightweight way to proxy commands 
- Will authentication work out of the box? Do we need to add client configuration for what service account to use, or can we make server side changes to support more types of credentials?

**Comment by nikhil-thomas** [comment]
@piyush-garg, @vinamra28

**Comment by wlynch** [comment]
https://github.com/tektoncd/results/tree/main/tools/tkn-results
