### ISSUE TITLE
[api] List ordering

### ISSUE THREAD

**Issue by wlynch** [tektoncd/results#85]
A common use case will be to order results by creation time (e.g. show me the most recent).

We should look into adding an ordering field to List methods to support this - https://google.aip.dev/132#ordering

**Comment by sbwsg** [comment]
I'll take a look into implementing this!

/assign

**Comment by wlynch** [comment]
Thanks Scott! Places we'll likely need changes: 

- Proto definition for [ListResults](https://github.com/tektoncd/results/blob/da219e11cb33f1ecb4a6815e3b39ad77b417d667/proto/v1alpha2/api.proto#L120) and [ListRecords](https://github.com/tektoncd/results/blob/da219e11cb33f1ecb4a6815e3b39ad77b417d667/proto/v1alpha2/api.proto#L162) (also [regen the proto libraries](https://github.com/tektoncd/results/blob/main/proto/README.md#regenerating-proto-libraries))
- DB queries made for [Results](https://github.com/tektoncd/results/blob/da219e11cb33f1ecb4a6815e3b39ad77b417d667/pkg/api/server/v1alpha2/results.go#L216) and [Records](https://github.com/tektoncd/results/blob/da219e11cb33f1ecb4a6815e3b39ad77b417d667/pkg/api/server/v1alpha2/records.go#L192)
