### ISSUE TITLE
Use jsonb instead of blob

### ISSUE THREAD

**Issue by jchesterpivotal** [tektoncd/results#99]
### Feature request

In the schema, the bodies of Tekton's resources are stored as `blob` types. Blobs are not suitable for indexing and do not allow easy querying by analysts or tools accessing the database instead of the gRPC service.

Switching to `jsonb` would allow for more efficient storage, make it possible to index records and enable rich querying via JSON operators.

**Comment by wlynch** [comment]
Thanks for the FR!

We haven't had a chance to look into indexing support, but this looks like a strong contender. I plan to spend some time this week looking into `jsonb` + and other alternatives. Stay tuned!

**Comment by wlynch** [comment]
Overdue follow up: jsonb seems reasonable, but since this will be a database migration we'll also need to provide tooling for migration. I'll add this to our next milestone!
